# Update wappalyzer and the Chrome feature names and create a PR if there were any changes
on:
  schedule:
    # Run Monthly on the 2nd of each month
    - cron: '12 2 2 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python3 -m pip install requests
      - name: Update Wappalyzer
        run: ./update_wappalyzer.sh
      - name: Update Features
        run: python3 internal/support/FEATURES/update.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          # token: ${{ secrets.PAT }}
          commit-message: Update Wappalyzer and Features
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: updates
          delete-branch: true
          title: 'Update Wappalyzer and Chrome Feature Names'
          draft: false
      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          #token: ${{ secrets.PAT }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: squash
